repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        exclude: 'jupyter'
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        exclude: 'jupyter'
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: 'jupyter'
